/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as RankingsIndexRouteImport } from './routes/rankings.index'
import { Route as RankingsBloodCastleRouteImport } from './routes/rankings.blood-castle'
import { Route as RankingsChaosCastleRouteImport } from './routes/rankings.chaos-castle'
import { Route as RankingsClassesRouteImport } from './routes/rankings.classes'
import { Route as RankingsDevilSquareRouteImport } from './routes/rankings.devil-square'
import { Route as RankingsGuildsRouteImport } from './routes/rankings.guilds'
import { Route as RankingsKillsRouteImport } from './routes/rankings.kills'
import { Route as RankingsLevelRouteImport } from './routes/rankings.level'
import { Route as RankingsMasterLevelRouteImport } from './routes/rankings.master-level'
import { Route as RankingsMasterResetRouteImport } from './routes/rankings.master-reset'
import { Route as RankingsMensalRouteImport } from './routes/rankings.mensal'
import { Route as RankingsPkRouteImport } from './routes/rankings.pk'
import { Route as RankingsResetRouteImport } from './routes/rankings.reset'
import { Route as RankingsSemanalRouteImport } from './routes/rankings.semanal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RankingsRoute,
} as any)
const RankingsBloodCastleRoute = RankingsBloodCastleRouteImport.update({
  id: '/blood-castle',
  path: '/blood-castle',
  getParentRoute: () => RankingsRoute,
} as any)
const RankingsChaosCastleRoute = RankingsChaosCastleRouteImport.update({
  id: '/chaos-castle',
  path: '/chaos-castle',
  getParentRoute: () => RankingsRoute,
} as any)
const RankingsClassesRoute = RankingsClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => RankingsRoute,
} as any)
const RankingsDevilSquareRoute = RankingsDevilSquareRouteImport.update({
  id: '/devil-square',
  path: '/devil-square',
  getParentRoute: () => RankingsRoute,
} as any)
const RankingsGuildsRoute = RankingsGuildsRouteImport.update({
  id: '/guilds',
  path: '/guilds',
  getParentRoute: () => RankingsRoute,
} as any)
const RankingsKillsRoute = RankingsKillsRouteImport.update({
  id: '/kills',
  path: '/kills',
  getParentRoute: () => RankingsRoute,
} as any)
const RankingsLevelRoute = RankingsLevelRouteImport.update({
  id: '/level',
  path: '/level',
  getParentRoute: () => RankingsRoute,
} as any)
const RankingsMasterLevelRoute = RankingsMasterLevelRouteImport.update({
  id: '/master-level',
  path: '/master-level',
  getParentRoute: () => RankingsRoute,
} as any)
const RankingsMasterResetRoute = RankingsMasterResetRouteImport.update({
  id: '/master-reset',
  path: '/master-reset',
  getParentRoute: () => RankingsRoute,
} as any)
const RankingsMensalRoute = RankingsMensalRouteImport.update({
  id: '/mensal',
  path: '/mensal',
  getParentRoute: () => RankingsRoute,
} as any)
const RankingsPkRoute = RankingsPkRouteImport.update({
  id: '/pk',
  path: '/pk',
  getParentRoute: () => RankingsRoute,
} as any)
const RankingsResetRoute = RankingsResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => RankingsRoute,
} as any)
const RankingsSemanalRoute = RankingsSemanalRouteImport.update({
  id: '/semanal',
  path: '/semanal',
  getParentRoute: () => RankingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rankings': typeof RankingsRouteWithChildren
  '/rankings/blood-castle': typeof RankingsBloodCastleRoute
  '/rankings/chaos-castle': typeof RankingsChaosCastleRoute
  '/rankings/classes': typeof RankingsClassesRoute
  '/rankings/devil-square': typeof RankingsDevilSquareRoute
  '/rankings/guilds': typeof RankingsGuildsRoute
  '/rankings/kills': typeof RankingsKillsRoute
  '/rankings/level': typeof RankingsLevelRoute
  '/rankings/master-level': typeof RankingsMasterLevelRoute
  '/rankings/master-reset': typeof RankingsMasterResetRoute
  '/rankings/mensal': typeof RankingsMensalRoute
  '/rankings/pk': typeof RankingsPkRoute
  '/rankings/reset': typeof RankingsResetRoute
  '/rankings/semanal': typeof RankingsSemanalRoute
  '/rankings/': typeof RankingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rankings/blood-castle': typeof RankingsBloodCastleRoute
  '/rankings/chaos-castle': typeof RankingsChaosCastleRoute
  '/rankings/classes': typeof RankingsClassesRoute
  '/rankings/devil-square': typeof RankingsDevilSquareRoute
  '/rankings/guilds': typeof RankingsGuildsRoute
  '/rankings/kills': typeof RankingsKillsRoute
  '/rankings/level': typeof RankingsLevelRoute
  '/rankings/master-level': typeof RankingsMasterLevelRoute
  '/rankings/master-reset': typeof RankingsMasterResetRoute
  '/rankings/mensal': typeof RankingsMensalRoute
  '/rankings/pk': typeof RankingsPkRoute
  '/rankings/reset': typeof RankingsResetRoute
  '/rankings/semanal': typeof RankingsSemanalRoute
  '/rankings': typeof RankingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rankings': typeof RankingsRouteWithChildren
  '/rankings/blood-castle': typeof RankingsBloodCastleRoute
  '/rankings/chaos-castle': typeof RankingsChaosCastleRoute
  '/rankings/classes': typeof RankingsClassesRoute
  '/rankings/devil-square': typeof RankingsDevilSquareRoute
  '/rankings/guilds': typeof RankingsGuildsRoute
  '/rankings/kills': typeof RankingsKillsRoute
  '/rankings/level': typeof RankingsLevelRoute
  '/rankings/master-level': typeof RankingsMasterLevelRoute
  '/rankings/master-reset': typeof RankingsMasterResetRoute
  '/rankings/mensal': typeof RankingsMensalRoute
  '/rankings/pk': typeof RankingsPkRoute
  '/rankings/reset': typeof RankingsResetRoute
  '/rankings/semanal': typeof RankingsSemanalRoute
  '/rankings/': typeof RankingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rankings'
    | '/rankings/blood-castle'
    | '/rankings/chaos-castle'
    | '/rankings/classes'
    | '/rankings/devil-square'
    | '/rankings/guilds'
    | '/rankings/kills'
    | '/rankings/level'
    | '/rankings/master-level'
    | '/rankings/master-reset'
    | '/rankings/mensal'
    | '/rankings/pk'
    | '/rankings/reset'
    | '/rankings/semanal'
    | '/rankings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rankings/blood-castle'
    | '/rankings/chaos-castle'
    | '/rankings/classes'
    | '/rankings/devil-square'
    | '/rankings/guilds'
    | '/rankings/kills'
    | '/rankings/level'
    | '/rankings/master-level'
    | '/rankings/master-reset'
    | '/rankings/mensal'
    | '/rankings/pk'
    | '/rankings/reset'
    | '/rankings/semanal'
    | '/rankings'
  id:
    | '__root__'
    | '/'
    | '/rankings'
    | '/rankings/blood-castle'
    | '/rankings/chaos-castle'
    | '/rankings/classes'
    | '/rankings/devil-square'
    | '/rankings/guilds'
    | '/rankings/kills'
    | '/rankings/level'
    | '/rankings/master-level'
    | '/rankings/master-reset'
    | '/rankings/mensal'
    | '/rankings/pk'
    | '/rankings/reset'
    | '/rankings/semanal'
    | '/rankings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RankingsRoute: typeof RankingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/': {
      id: '/rankings/'
      path: '/'
      fullPath: '/rankings/'
      preLoaderRoute: typeof RankingsIndexRouteImport
      parentRoute: typeof RankingsRoute
    }
    '/rankings/blood-castle': {
      id: '/rankings/blood-castle'
      path: '/blood-castle'
      fullPath: '/rankings/blood-castle'
      preLoaderRoute: typeof RankingsBloodCastleRouteImport
      parentRoute: typeof RankingsRoute
    }
    '/rankings/chaos-castle': {
      id: '/rankings/chaos-castle'
      path: '/chaos-castle'
      fullPath: '/rankings/chaos-castle'
      preLoaderRoute: typeof RankingsChaosCastleRouteImport
      parentRoute: typeof RankingsRoute
    }
    '/rankings/classes': {
      id: '/rankings/classes'
      path: '/classes'
      fullPath: '/rankings/classes'
      preLoaderRoute: typeof RankingsClassesRouteImport
      parentRoute: typeof RankingsRoute
    }
    '/rankings/devil-square': {
      id: '/rankings/devil-square'
      path: '/devil-square'
      fullPath: '/rankings/devil-square'
      preLoaderRoute: typeof RankingsDevilSquareRouteImport
      parentRoute: typeof RankingsRoute
    }
    '/rankings/guilds': {
      id: '/rankings/guilds'
      path: '/guilds'
      fullPath: '/rankings/guilds'
      preLoaderRoute: typeof RankingsGuildsRouteImport
      parentRoute: typeof RankingsRoute
    }
    '/rankings/kills': {
      id: '/rankings/kills'
      path: '/kills'
      fullPath: '/rankings/kills'
      preLoaderRoute: typeof RankingsKillsRouteImport
      parentRoute: typeof RankingsRoute
    }
    '/rankings/level': {
      id: '/rankings/level'
      path: '/level'
      fullPath: '/rankings/level'
      preLoaderRoute: typeof RankingsLevelRouteImport
      parentRoute: typeof RankingsRoute
    }
    '/rankings/master-level': {
      id: '/rankings/master-level'
      path: '/master-level'
      fullPath: '/rankings/master-level'
      preLoaderRoute: typeof RankingsMasterLevelRouteImport
      parentRoute: typeof RankingsRoute
    }
    '/rankings/master-reset': {
      id: '/rankings/master-reset'
      path: '/master-reset'
      fullPath: '/rankings/master-reset'
      preLoaderRoute: typeof RankingsMasterResetRouteImport
      parentRoute: typeof RankingsRoute
    }
    '/rankings/mensal': {
      id: '/rankings/mensal'
      path: '/mensal'
      fullPath: '/rankings/mensal'
      preLoaderRoute: typeof RankingsMensalRouteImport
      parentRoute: typeof RankingsRoute
    }
    '/rankings/pk': {
      id: '/rankings/pk'
      path: '/pk'
      fullPath: '/rankings/pk'
      preLoaderRoute: typeof RankingsPkRouteImport
      parentRoute: typeof RankingsRoute
    }
    '/rankings/reset': {
      id: '/rankings/reset'
      path: '/reset'
      fullPath: '/rankings/reset'
      preLoaderRoute: typeof RankingsResetRouteImport
      parentRoute: typeof RankingsRoute
    }
    '/rankings/semanal': {
      id: '/rankings/semanal'
      path: '/semanal'
      fullPath: '/rankings/semanal'
      preLoaderRoute: typeof RankingsSemanalRouteImport
      parentRoute: typeof RankingsRoute
    }
  }
}

interface RankingsRouteChildren {
  RankingsBloodCastleRoute: typeof RankingsBloodCastleRoute
  RankingsChaosCastleRoute: typeof RankingsChaosCastleRoute
  RankingsClassesRoute: typeof RankingsClassesRoute
  RankingsDevilSquareRoute: typeof RankingsDevilSquareRoute
  RankingsGuildsRoute: typeof RankingsGuildsRoute
  RankingsKillsRoute: typeof RankingsKillsRoute
  RankingsLevelRoute: typeof RankingsLevelRoute
  RankingsMasterLevelRoute: typeof RankingsMasterLevelRoute
  RankingsMasterResetRoute: typeof RankingsMasterResetRoute
  RankingsMensalRoute: typeof RankingsMensalRoute
  RankingsPkRoute: typeof RankingsPkRoute
  RankingsResetRoute: typeof RankingsResetRoute
  RankingsSemanalRoute: typeof RankingsSemanalRoute
  RankingsIndexRoute: typeof RankingsIndexRoute
}

const RankingsRouteChildren: RankingsRouteChildren = {
  RankingsBloodCastleRoute: RankingsBloodCastleRoute,
  RankingsChaosCastleRoute: RankingsChaosCastleRoute,
  RankingsClassesRoute: RankingsClassesRoute,
  RankingsDevilSquareRoute: RankingsDevilSquareRoute,
  RankingsGuildsRoute: RankingsGuildsRoute,
  RankingsKillsRoute: RankingsKillsRoute,
  RankingsLevelRoute: RankingsLevelRoute,
  RankingsMasterLevelRoute: RankingsMasterLevelRoute,
  RankingsMasterResetRoute: RankingsMasterResetRoute,
  RankingsMensalRoute: RankingsMensalRoute,
  RankingsPkRoute: RankingsPkRoute,
  RankingsResetRoute: RankingsResetRoute,
  RankingsSemanalRoute: RankingsSemanalRoute,
  RankingsIndexRoute: RankingsIndexRoute,
}

const RankingsRouteWithChildren = RankingsRoute._addFileChildren(
  RankingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RankingsRoute: RankingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
